use sakila;

/*Write SQL queries to perform the following tasks using the Sakila database:/*

/*1. List the number of films per category.*/

select * from film_category fc ;

select count(sf.film_id) as "Films number", name 
from sakila.film sf
left join sakila.film_category sfc 
on sf.film_id = sfc.film_id
join sakila.category sc 
on sfc.category_id = sc.category_id
group by name;


/*2. Retrieve the store ID, city, and country for each store.*/


select store_ID, city, country
from sakila.store ss 
join sakila.address sa
on ss.address_id = sa.address_id
join sakila.city c 
on sa.city_id = c.city_id
join sakila.country c2  
on c.country_id = c2.country_id;


/*3. Calculate the total revenue generated by each store in dollars.*/

select * from payment;

select ss.store_id, sum(sp.amount) as total_revenue
from sakila.store ss
join sakila.customer sc
on ss.store_id = sc.store_id
join sakila.payment sp
on sc.customer_id = sp.customer_id
group by store_id;


/*4. Determine the average running time of films for each category.*/

SELECT c.name, avg(f.LENGTH) as Avg_runningtime
from film f 
join film_category fc 
on f.film_id = fc.film_id 
join category c 
on fc.category_id = c.category_id 
group by c.category_id;



Bonus:

5.Identify the film categories with the longest average running time.
6.Display the top 10 most frequently rented movies in descending order.
7.Determine if "Academy Dinosaur" can be rented from Store 1.
8.Provide a list of all distinct film titles, along with their availability status in the inventory. 
Include a column indicating whether each title is 'Available' or 'NOT available.' 
Note that there are 42 titles that are not in the inventory, and this information can be obtained using 
a CASE statement combined with IFNULL."
Here are some tips to help you successfully complete the lab:

Tip 1: This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:

Make sure you understand the relationships between the tables in the database. This will help you determine which tables to join and which columns to use in your joins.
Identify a common column for both tables to use in the ON section of the join. If there isn't a common column, you may need to add another table with a common column.
Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
Determine which table you want to include all records from. This will help you decide which type of JOIN to use. If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. If you want records from both tables only where there is a match, use an INNER JOIN.
Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.
Write the query
Tip 2: Break down the problem into smaller, more manageable parts. For example, you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. Test your queries as you go, and check the output carefully to make sure it matches what you expect. This process takes time, so be patient and go step by step to build your query incrementally.